app/urls.py
from django.urls import path
from . import  views


app_name = 'app'


urlpatterns = [
    path('', views.home, name='home'),
    path('body-progress/', views.body_progress, name='body_progress'),
    path('diet/', views.diet, name='diet'),
    path('training/', views.training, name='training'),
    path('chat-coach/', views.chat_coach, name='chat_coach'),
    #settigs
    path('settings/general/', views.settings_general, name='settings_general'),
    path('settings/billing/', views.settings_billing, name='settings_billing'),
    path('settings/security/', views.settings_security, name='settings_security'),
    path('settings/notifications/', views.settings_notifications, name='settings_notifications'),
    path('sample/', views.sample, name='sample'),
]

app_rama/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('preview/', include('app.urls', namespace='app')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
    path('', include('overview_app.urls', namespace='overview_app')),
    path('accounts/', include('allauth.urls')),  # potrzebne do wysłania emaila
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

overview_app/urls.py
from django.urls import path
from . import views


app_name = 'overview_app'


urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('pricing/', views.pricing, name='pricing'),
    path('functions/', views.functions, name='functions'),
    path('vote-for-news/', views.vote_for_news, name='vote_for_news'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
]

overview_app/models.py
from django.db import models
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFit, ResizeToFill
from ckeditor.fields import RichTextField


class Contact(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    data = models.CharField(max_length=200, verbose_name='Preferred date and time of the video call')


class ContactAdvanced(models.Model):
    name = models.CharField(max_length=200, verbose_name='Name')
    surname = models.CharField(max_length=200, verbose_name='Surname')
    email = models.EmailField(verbose_name='E-mail')
    contact = models.TextField(verbose_name='Message content')



class TermsAndConditions(models.Model):
    terms = models.TextField()
    privacy = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    title_basic = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)



class Article(models.Model):
    category = models.CharField(max_length=200, verbose_name='Kategoria rankingu')
    name = models.CharField(max_length=200, verbose_name='Główny tytuł wyświetlany w podglądzie',)
    small_description = models.TextField(verbose_name='Krótki opis wyświetlany w podglądzie')
    author = models.CharField(max_length=200, verbose_name='Autor tematu')
    author_img = ProcessedImageField(upload_to='profile-pictures',
                                     verbose_name='Zdjęcie profilowe autora (preferowany rozmiar 200x200)',
                                processors=[ResizeToFill(200, 200)],
                                format='JPEG',
                                options={'quality': 100})
    title = models.CharField(max_length=500, verbose_name='Tytuł')
    basic_img = ProcessedImageField(upload_to='profile-pictures',
                                    verbose_name='Zdjęcie główne (preferowany rozmiar 923x498)',
                                processors=[ResizeToFill(923, 498)],
                                format='JPEG',
                                options={'quality': 100})
    content = RichTextField(verbose_name='Treść tematu')
    slug = models.SlugField(verbose_name="Nazwa wyświetlana w adresie url: http//domain.com/...",)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_at']
        verbose_name = '2A - BLOG - Pozostałe rankingi'
        verbose_name_plural = '2A - BLOG - Pozostałe rankingi'


class ArticleList(models.Model):
    for_article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='Dla artykułu')
    name = models.CharField(max_length=200, verbose_name='Nazwa firmy/Instancji')
    content = models.TextField(blank=True, null=True, verbose_name='Treść/opis (minimalistyczny, przed opisem głównym)')
    image = ProcessedImageField(upload_to='profile-pictures',
                                blank=True, null=True,
                                verbose_name='Zdjęcie główne (preferowany rozmiar 923x328)',
                                processors=[ResizeToFill(928, 328)],
                                format='JPEG',
                                options={'quality': 100})
    logo = ProcessedImageField(upload_to='profile-pictures',
                                blank=True, null=True,
                                verbose_name='Logo',
                                processors=[ResizeToFit(250, 250)],
                                format='JPEG',
                                options={'quality': 100})
    description = RichTextField(blank=True, null=True, verbose_name='Pełna treść (opis główny firmy/isntancji)')

    def __str__(self):
        return '%s - %s' % (self.for_article, self.name)

    class Meta:
        verbose_name = '2B - BLOG - Przedmioty do pozostałych rankingów'
        verbose_name_plural = '2B - BLOG - Przedmioty do pozostałych rankingów'

overview_app/forms.py
from django import forms
from .models import Contact, ContactAdvanced
from django.forms import Textarea



class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = {'name', 'phone', 'data'}


class ContactAdvancedForms(forms.ModelForm):
    class Meta:
        model = ContactAdvanced
        fields = {'name', 'surname', 'email', 'contact'}
        widgets = {'contact': Textarea(attrs={'rows': '6',
                                              'class': 'form-control',
                                              'placeholder': 'Write the content of the message sent to our team...'})}

overview_app/views.py
from django.shortcuts import render
from .forms import ContactForm, ContactAdvancedForms
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Article, TermsAndConditions



def home(request):
    send = request.session.get('send')
    if send:
        request.session['send'] = None

    #contact form
    if request.method == 'POST' and 'buttonSend' in request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['send'] = 'Thank you, the form has been completed correctly. Wait for our employee to contact you.'
            return HttpResponseRedirect(reverse('overview_app:home'))
    else:
        form = ContactForm()

    context = {'send': send,
               'form': form}
    return render(request, 'overview_app/home.html', context)



def contact(request):
    #contact form
    if request.method == 'POST' and 'buttonSend' in request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['send'] = 'Thank you, the form has been completed correctly. Wait for our employee to contact you.'
            return HttpResponseRedirect(reverse('overview_app:home'))
    else:
        form = ContactForm()

    contact_form = ContactAdvancedForms()

    context = {'form': form,
               'contact_form': contact_form}
    return render(request, 'overview_app/contact.html', context)



def pricing(request):
    #contact form
    if request.method == 'POST' and 'buttonSend' in request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['send'] = 'Thank you, the form has been completed correctly. Wait for our employee to contact you.'
            return HttpResponseRedirect(reverse('overview_app:home'))
    else:
        form = ContactForm()

    context = {'form': form}
    return render(request, 'overview_app/pricing.html', context)


def functions(request):
    #functions
    obj = Article.objects.last()

    #contact form
    if request.method == 'POST' and 'buttonSend' in request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['send'] = 'Thank you, the form has been completed correctly. Wait for our employee to contact you.'
            return HttpResponseRedirect(reverse('overview_app:home'))
    else:
        form = ContactForm()

    context = {'form': form,
               'obj': obj}
    return render(request, 'overview_app/functions.html', context)



def vote_for_news(request):
    #contact form
    if request.method == 'POST' and 'buttonSend' in request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['send'] = 'Thank you, the form has been completed correctly. Wait for our employee to contact you.'
            return HttpResponseRedirect(reverse('overview_app:home'))
    else:
        form = ContactForm()

    context = {'form': form}
    return render(request, 'overview_app/vote_for_news.html', context)



def terms(request):
    #specific
    obj = TermsAndConditions.objects.last()

    #contact form
    if request.method == 'POST' and 'buttonSend' in request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['send'] = 'Thank you, the form has been completed correctly. Wait for our employee to contact you.'
            return HttpResponseRedirect(reverse('overview_app:home'))
    else:
        form = ContactForm()

    context = {'form': form,
               'obj': obj}
    return render(request, 'overview_app/terms.html', context)



def privacy(request):
    #specific
    obj = TermsAndConditions.objects.last()

    #contact form
    if request.method == 'POST' and 'buttonSend' in request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['send'] = 'Thank you, the form has been completed correctly. Wait for our employee to contact you.'
            return HttpResponseRedirect(reverse('overview_app:home'))
    else:
        form = ContactForm()

    context = {'form': form,
               'obj': obj}
    return render(request, 'overview_app/privacy.html', context)

overview_app/templates/overview_app/contact.html
{% load static %}
{% spaceless %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  
  <head> <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="BestCoach.app - Best application for personal trainers">
    <meta name="keywords" content="BestCoach.app - Best application for personal trainers">
    <meta name="author" content="BestCoach.app">
    
    
    <!-- Favicon icon-->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets_overview/images/favicon/icon.png' %}">
   
    
    <!-- Libs CSS -->
    <link href="{% static 'assets_overview/fonts/feather/feather.css' %}" rel="stylesheet">
    <link href="{% static 'assets_overview/libs/bootstrap-icons/font/bootstrap-icons.css' %}" rel="stylesheet" />
    <link href="{% static 'assets_overview/libs/@mdi/font/css/materialdesignicons.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets_overview/libs/simplebar/dist/simplebar.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets_overview/libs/@fancyapps/fancybox/dist/jquery.fancybox.min.css' %}">
    
    
    <!-- Theme CSS -->
    <link rel="stylesheet" href="{% static 'assets_overview/css/theme.min.css' %}">
    <title>BestCoach.app - Contact </title>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-L1EXNB7BNC"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-L1EXNB7BNC');
    </script>
  </head>
  
  <body class="bg-white">

  
    <!-- Page content -->
  <main>
  
      {% include "overview_app/basic/navbar.html" %}
      
  
  <!-- Page Content -->
  <section class="py-lg-15 py-10 bg-light mt-1">
    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-md-6  col-12 ">
          <!-- caption-->
          <h1 class="fw-bold mb-1 display-3">Contact us</h1>
          <!-- para -->
          <p class="mb-5 text-dark ">If you have any questions, please contact our team. We will be happy to answer all of them. If you want to arrange a presentation of the application, use the button in the upper right corner.</p>
        </div>
        <div class="col-md-6 col-12">
        </div>
      </div>

    </div>
  </section>
  <section class="mt-n8">
    <!-- container  -->
    <div class="container">
      <div class="card rounded-3 shadow-sm">
        <div class="row">
          <div class="col-md-4  col-12 border-end-md ">
            <!-- features  -->
            <div class=" border-bottom border-bottom-md-0 mb-3 mb-lg-0">
              <div class="p-5">
                <div class="mb-4">
                  <img src="{% static 'assets_overview/images/icons/1.png' %}" class="rounded" alt="Cinque Terre" style="height: 47px;">
                </div>
                <!-- heading  -->
                <h3 class="fw-semi-bold">E-mail contact <i class="bi bi-envelope-at"></i></h3>
                <!-- para  -->
                <p>If you have general questions for our team, please contact us via the email address below.</p>
                <!-- button  -->
                <a href="help-center-faq.html" class="link-primary fw-semi-bold">office@bestcoach.app</a>
              </div>
            </div>
          </div>
          <div class="col-md-4  col-12  border-end-md">
            <!-- features  -->
            <div class="border-bottom border-bottom-md-0 mb-3 mb-lg-0">
              <div class="p-5">
                <div class="mb-4">
                  <img src="{% static 'assets_overview/images/icons/2.png' %}" class="rounded" alt="Cinque Terre" style="height: 47px;">
                </div>
                <!-- heading  -->
                <h3 class="fw-semi-bold">Telephone contact
                </h3>
                <!-- para  -->
                <p>If it is more convenient for you to talk by phone, please contact us via the phone number below.</p>
                <!-- button  -->
                <a href="help-center-guide.html" class="link-primary fw-semi-bold">+1 (352) 462 4327</a>
              </div>
            </div>
          </div>
          <div class="col-md-4  col-12">
            <div>
              <div class="p-5">
                <div class="mb-4">
                  <img src="{% static 'assets_overview/images/icons/3.png' %}" class="rounded" alt="Cinque Terre" style="height: 47px;">
                </div>
                <!-- heading  -->
                <h3 class="fw-semi-bold">Technical questions</h3>
                <!-- para  -->
                <p>If you have questions about our algorithm or other technical questions, please contact us via the email below.</p>
                <!-- button  -->
                <a href="help-center-support.html" class="link-primary fw-semi-bold">technical-team@bestcoach.app</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
   <!-- container  -->
  <section class="py-lg-16 py-10">
    <div class="container">
      <div class="row">
        <div class="offset-lg-2 col-lg-6  col-12">
          <div class="mb-8 pe-lg-14">
             <!-- heading  -->
            <h2 class="pe-lg-12 mb-4 h1 fw-semi-bold">Contact form</h2>
            <p class="lead">If you have any questions or just want to say hello, please write to us 📝</p>
          </div>
        </div>
      </div>
      <div class="row" id="contactForm">
        <div class="offset-lg-2 col-lg-8 col-12">
        
          {% if send %}
          <div class="alert alert-success" role="alert">
            <b>Done!</b> {{ send }}
          </div>
          {% endif %}
          
          <form method="POST" action="#contactForm">
          {% csrf_token %}
             <!-- accordions  -->
            <div class="accordion accordion-flush" id="accordionExample">
            
              <div class="row">
                <div class="col-md-6">
                  {{ contact_form.name|as_crispy_field }}
                </div>
                <div class="col-md-6">
                  {{ contact_form.surname|as_crispy_field }}
                </div>
              </div>
              
              <div class="row">
                <div class="col-md-12">
                  {{ contact_form.email|as_crispy_field }}
                </div>
              </div>
              
              <div class="row">
                <div class="col-md-12">
                  {{ contact_form.contact|as_crispy_field }}
                </div>
              </div>
              
              <div class="row">
                <div class="col-md-12">
                  <button class="btn btn-primary" type="submit" name="contactFormButton">Send message</button>
                </div>
              </div>
              
              <!-- Card  -->
            </div>
          </form>

        </div>
      </div>
    </div>
  </section>
 <!-- container  -->
  <section class="pb-lg-16 pb-10">
    <div class="container">
      <div class="row">
        <div class="offset-lg-2 col-lg-4  col-12">
          <div class="mb-8">
            <h2 class="mb-0 h1 fw-semi-bold">Are you looking for something different?</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="offset-lg-2 col-lg-8  col-12">
          <div class="row">
            <div class="col-md-6 col-12">
               <!-- card  -->
              <div class="card border mb-md-0 mb-4">
                 <!-- card body  -->
                <div class="card-body">
                  <div class="mb-3">
                    <img src="{% static 'assets_overview/images/icons/4.png' %}" class="rounded" alt="Cinque Terre" style="height: 55px;">
                  </div>
                   <!-- para  -->
                  <h3 class="mb-2 fw-semi-bold">Features available</h3>
                  <p>Jeżeli chcesz porównać portale z perspektywy swojej kategorii produktowej i innych parametrów naciśnij poniższy przycisk.</p>
                     <!-- btn  -->
                  <a href="{% url 'overview_app:functions' %}" class="btn btn-primary btn-sm">See the functionalities <i class="bi bi-arrow-right-short"></i></a>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-12">
               <!-- card  -->
              <div class="card border">
                 <!-- card body  -->
                <div class="card-body">
                  <div class="mb-3">
                    <img src="{% static 'assets_overview/images/icons/5.png' %}" class="rounded" alt="Cinque Terre" style="height: 55px;">
                  </div>
                   <!-- para  -->
                  <h3 class="mb-2 fw-semi-bold">Application preview</h3>
                  <p>Podoba Ci się to co robimy lub znalazłeś idealny portal przez naszą stronę internetową, okaż naszemu zespołowi wsparcie.</p>
                     <!-- btn  -->
                  <a href="{% url 'app:home' %}" class="btn btn-outline-secondary btn-sm">Live app preview <i class="bi bi-eye"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
  
    <!-- Footer -->
    <!-- footer -->
    {% include "overview_app/basic/footer.html" %}
    
    
    <!-- Scripts -->
    <!-- Libs JS -->
    <script src="{% static 'assets_overview/libs/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'assets_overview/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets_overview/libs/simplebar/dist/simplebar.min.js' %}"></script>
    <script src="{% static 'assets_overview/libs/@fancyapps/fancybox/dist/jquery.fancybox.min.js' %}"></script>
    
    
    <!-- Theme JS -->
    <script src="{% static 'assets_overview/js/theme.min.js' %}"></script>
    
    
  </body>
  
</html>
{% endspaceless %}

overview_app/templates/overview_app/functions.html
{% spaceless %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="BestCoach.app - Best application for personal trainers">
    <meta name="keywords" content="BestCoach.app - Best application for personal trainers">
    <meta name="author" content="BestCoach.app">
    
    <!-- Favicon icon-->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets_overview/images/favicon/icon.png' %}">
    
    
    <!-- Libs CSS -->
    <link href="{% static 'assets_overview/fonts/feather/feather.css' %}" rel="stylesheet">
    <link href="{% static 'assets_overview/libs/bootstrap-icons/font/bootstrap-icons.css' %}" rel="stylesheet" />
    <link href="{% static 'assets_overview/libs/@mdi/font/css/materialdesignicons.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets_overview/libs/simplebar/dist/simplebar.min.css' %}" rel="stylesheet">
    
    
    <!-- Theme CSS -->
    <link rel="stylesheet" href="{% static 'assets_overview/css/theme.min.css' %}">
    <link href="{% static 'assets_overview/libs/tiny-slider/dist/tiny-slider.css' %}" rel="stylesheet">
    <title>BestCoach.app - Application features overview </title>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-L1EXNB7BNC"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-L1EXNB7BNC');
    </script>
  </head>
  
  <body class="bg-white">
    <!-- Page content -->
    <main class="mb-0">
      <!-- navbar login -->
      {% include "overview_app/basic/navbar.html" %}
      
      <!-- Content -->
      <section class="py-4 py-lg-8 pb-14">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-xl-8 col-lg-8 col-md-12 col-12 mb-2">
              <div class="text-center mb-4">
                <a href="#" class="fs-5 fw-semi-bold d-block mb-4 text-primary">{{ obj.category }}</a>
                <h1 class="display-3 fw-bold mb-4">{{ obj.name }}</h1>
                <span class="mb-3 d-inline-block">{{ obj.created_at }}</span>
              </div>
            </div>
          </div>
          {% if obj.basic_img %}
          <div class="row justify-content-center">
            <!-- Image -->
            <div class="col-xl-10 col-lg-10 col-md-12 col-12 mb-6">
              <img src="{{ obj.basic_img.url }}" alt="" class="img-fluid rounded-3 w-100">
            </div>
          </div>
          {% endif %}
          <div class="row justify-content-center">
            <div class="col-xl-8 col-lg-8 col-md-12 col-12 mb-2">
              <!-- Descriptions -->
              <div>
                <div class="mb-4">
                  <p class="lead text-dark">
                    {{ obj.content|safe }}
                  </p>
                </div>
                
                
                {% for sub_article in obj.articlelist_set.all %}
                <hr class="mt-lg-6 mb-lg-6 my-md-6">
                <!-- Img alignment -->
                <div class="mb-5">
                  <h2 class="mb-2">{{ sub_article.name }}</h2>
                  {% if sub_article.content %}
                  <p>
                    {{ sub_article.content|linebreaks }}
                  </p>
                  {% endif %}

                  <div class="mt-4">
                    <!-- Img  -->
                    {% if sub_article.image %}
                    <img src="{{ sub_article.image.url }}" alt="" class="img-fluid me-4 rounded-3" />
                    {% endif %}
                    
                    {% if sub_article.logo %}
                    <img src="{{ sub_article.logo.url }}" alt="" class="me-4 rounded-3" style="height: 45px;"/>
                    {% endif %}
                    
                    {% if sub_article.description %}
                    <div>
                      <p>
                        {{ sub_article.description|safe }}
                      </p>
                    </div>
                    {% endif %}
                    
                  </div>
                </div>
                {% endfor %}
                
              </div>
              
              <!-- Media -->
              <hr class="mt-8 mb-5">
              <div class="d-flex justify-content-between align-items-center mb-5">
                <div class="d-flex align-items-center">
                  <img src="{{ obj.author_img.url }}" alt="" class="rounded-circle avatar-md">
                  <div class="ms-2 lh-1">
                    <h5 class="mb-1 ">{{ obj.author }}</h5>
                    <span class="text-primary">Administrator</span>
                  </div>
                </div>
                <div>
                  <span class="ms-2 text-muted">Last edit time: <b class="text-primary">{{ obj.created_at }}</b></span>
                </div>
              </div>
              <!-- Subscribe to Newsletter -->
              <div class="py-15">
                <div class="card">
                  <div class="card-body">
                    <div class="text-center mb-4">
                      <h2 class="display-4 fw-bold mb-3">Vote for new features 👍!</h2>
                      <p class="mb-0 lead">The purpose of our application is to facilitate your daily work as a personal trainer. Choose what new features we should implement or vote for the ones currently selected by users.</p>
                    </div>
                    <!-- Form -->
                    <div class="row text-center">
                      <div class="mb-3">
                        <a class="btn btn-primary btn-lg" href="{% url 'overview_app:vote_for_news' %}">Go to vote <i class="bi bi-arrow-right-short"></i></a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </section>
    </main>
    
    <!-- Footer -->
    {% include "overview_app/basic/footer.html" %}
    
    <!-- Libs JS -->
    <script src="{% static 'assets_overview/libs/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'assets_overview/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets_overview/libs/simplebar/dist/simplebar.min.js' %}"></script>
    
    
    <!-- Theme JS -->
    <script src="{% static 'assets_overview/js/theme.min.js' %}"></script>
    
    
    <script src="{% static 'assets_overview/libs/tiny-slider/dist/min/tiny-slider.js' %}"></script>
    <script src="{% static 'assets_overview/libs/@popperjs/core/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'assets_overview/libs/tippy.js/dist/tippy-bundle.umd.min.js' %}"></script>
    <script src="{% static 'assets_overview/js/vendors/tnsSlider.js' %}"></script>
    <script src="{% static 'assets_overview/js/vendors/tooltip.js' %}"></script>
    
  </body>
  
</html>
{% endspaceless %}