app/urls.py
from django.urls import path
from . import  views


app_name = 'app'


urlpatterns = [
    path('', views.home, name='home'),
    path('body-progress/', views.body_progress, name='body_progress'),
    path('diet/', views.diet, name='diet'),
    path('training/', views.training, name='training'),
    path('chat-coach/', views.chat_coach, name='chat_coach'),
    #settigs
    path('settings/general/', views.settings_general, name='settings_general'),
    path('settings/billing/', views.settings_billing, name='settings_billing'),
    path('settings/security/', views.settings_security, name='settings_security'),
    path('settings/notifications/', views.settings_notifications, name='settings_notifications'),
    path('sample/', views.sample, name='sample'),
]

app_rama/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('preview/', include('app.urls', namespace='app')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
    path('', include('overview_app.urls', namespace='overview_app')),
    path('accounts/', include('allauth.urls')),  # potrzebne do wysłania emaila
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/basic/header.html
{% load static %}
<header class="top-0 overlap-10 bg-surface-primary border-bottom d-none d-lg-block">
  <div class="container-fluid py-4">
    <div class="row align-items-center">
      <div class="col">
        <div class="d-flex align-items-center gap-4">
          <h1 class="h3 ls-tight">👋 Welcome Alexander!</h1>
        </div>
      </div>
      <div class="col-auto">
        <div class="hstack gap-2 justify-content-end">
          <a href="#" class="text-sm text-muted text-primary-hover font-semibold me-2 d-none d-md-block" data-bs-toggle="modal" data-bs-target="#testVersionModal"><i class="bi bi-question-circle-fill"></i>
            <span class="d-none d-sm-inline ms-2">Need help?</span>
          </a>
          <a href="{% url 'overview_app:home' %}" class="btn btn-sm btn-dark border-base d-none d-md-block"><span>Logout</span></a>
        </div>
      </div>
    </div>
  </div>
</header>

app/templates/app/basic/modal_test_version.html
{% load static %}
<div class="modal fade" id="testVersionModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <div class="row">
          <div class="col-12 text-center">
            
            <p class="mt-4">You are using the demo version. You have limited rights to some options.</p>
            <img src="{% static 'img/900x900/warning_symbol_1.png' %}" class="img-fluid" alt="...">
          
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/templates/app/basic/navbar.html
{% load static %}
<nav class="navbar show navbar-vertical h-lg-screen navbar-expand-lg px-0 py-3 navbar-light bg-white border-bottom border-bottom-lg-0 border-end-lg " id="sidebar">
  <div class="container-fluid">
    <!-- Toggler -->
    <button class="navbar-toggler ms-n2" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarCollapse" aria-controls="sidebarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Brand -->
    <a class="navbar-brand py-lg-2 mb-lg-5 px-lg-6 me-0" href="{% url 'app:home' %}">
      <img src="{% static 'img/logos/clever-primary.svg' %}" alt="...">
    </a>
    <!-- User menu (mobile) -->
    <div class="navbar-user d-lg-none">
      <!-- Dropdown -->
      <div class="dropdown">
        <!-- Toggle -->
        <a href="#" id="sidebarAvatar" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <div class="avatar-parent-child">
            <img alt="..." src="{% static 'img/people/img-profile.jpg' %}" class="avatar avatar- rounded-circle">
            <span class="avatar-child avatar-badge bg-success"></span>
          </div>
        </a>
        <!-- Menu -->
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="sidebarAvatar">
          <a href="#" class="dropdown-item">Profile</a>
          <a href="#" class="dropdown-item">Settings</a>
          <a href="#" class="dropdown-item">Billing</a>
          <hr class="dropdown-divider">
          <a href="#" class="dropdown-item">Logout</a>
        </div>
      </div>
    </div>
    <!-- Collapse -->
    <div class="collapse navbar-collapse" id="sidebarCollapse">
      <!-- Navigation -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link py-2" href="{% url 'app:home' %}">
            <i class="bi bi-house-door-fill"></i> Home page
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link py-2" href="{% url 'app:diet' %}">
            <i class="bi bi-egg-fried"></i> Diet plan
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link py-2" href="{% url 'app:training' %}">
            <i class="bi bi-bicycle"></i> Training plan
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link py-2" href="{% url 'app:body_progress' %}">
            <i class="bi bi-person-lines-fill"></i> Body progress
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link py-2" href="{% url 'app:chat_coach' %}">
            <i class="bi bi-chat-dots"></i> Coach chat
          </a>
        </li>
      </ul>
      <!-- Divider -->
      <hr class="navbar-divider my-4 opacity-70">
      <!-- Documentation -->
      <ul class="navbar-nav">
        <li>
          <span class="nav-link text-xs font-semibold text-uppercase text-muted ls-wide">
            My profile
          </span>
        </li>
        <li class="nav-item">
          <a class="nav-link py-2" href="{% url 'app:settings_notifications' %}">
            <i class="bi bi-bell"></i> Notifications
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link py-2" href="{% url 'app:settings_general' %}">
            <i class="bi bi-gear"></i> General settings
          </a>
        </li>
      </ul>
      <!-- Divider -->
      <hr class="navbar-divider my-4 opacity-70">
      <!-- Documentation -->
      <ul class="navbar-nav">
        <li>
          <span class="nav-link text-xs font-semibold text-uppercase text-muted ls-wide">
            Other
          </span>
        </li>
        <li class="nav-item">
          <a class="nav-link py-2" href="{% url 'overview_app:home' %}">
            <i class="bi bi-box-arrow-right"></i> Logout
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/templates/app/basic/settings_header.html
{% load static %}
<header>
  <div class="container-fluid">
    <div class="border-bottom pt-6">
      <div class="row align-items-center">
        <div class="col-sm-6 col-12">
          <!-- Title -->
          <h1 class="h2 ls-tight">
            {{ template_name }}
          </h1>
        </div>
        <!-- Actions -->
        <div class="col-sm-6 col-12">
        </div>
      </div>
      <!-- Nav -->
      <ul class="nav nav-tabs overflow-x border-0">
        <li class="nav-item">
          <a href="{% url 'app:settings_general' %}" class="nav-link {% if activation_tab == 1 %}active{% endif %}">General</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link {% if activation_tab == 2 %}active{% endif %}" data-bs-toggle="modal" data-bs-target="#testVersionModal">Billing</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link {% if activation_tab == 3 %}active{% endif %}" data-bs-toggle="modal" data-bs-target="#testVersionModal">Security</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'app:settings_notifications' %}" class="nav-link {% if activation_tab == 4 %}active{% endif %}">Notifications</a>
        </li>
      </ul>
    </div>
  </div>
</header>