app/urls.py
from django.urls import path
from . import  views


app_name = 'app'


urlpatterns = [
    path('', views.home, name='home'),
    path('body-progress/', views.body_progress, name='body_progress'),
    path('diet/', views.diet, name='diet'),
    path('training/', views.training, name='training'),
    path('chat-coach/', views.chat_coach, name='chat_coach'),
    #settigs
    path('settings/general/', views.settings_general, name='settings_general'),
    path('settings/billing/', views.settings_billing, name='settings_billing'),
    path('settings/security/', views.settings_security, name='settings_security'),
    path('settings/notifications/', views.settings_notifications, name='settings_notifications'),
    path('sample/', views.sample, name='sample'),
]

app_rama/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('preview/', include('app.urls', namespace='app')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
    path('', include('overview_app.urls', namespace='overview_app')),
    path('accounts/', include('allauth.urls')),  # potrzebne do wysłania emaila
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

overview_app/urls.py
from django.urls import path
from . import views


app_name = 'overview_app'


urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('pricing/', views.pricing, name='pricing'),
    path('functions/', views.functions, name='functions'),
    path('vote-for-news/', views.vote_for_news, name='vote_for_news'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
]

overview_app/models.py
from django.db import models
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFit, ResizeToFill
from ckeditor.fields import RichTextField


class Contact(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    data = models.CharField(max_length=200, verbose_name='Preferred date and time of the video call')


class ContactAdvanced(models.Model):
    name = models.CharField(max_length=200, verbose_name='Name')
    surname = models.CharField(max_length=200, verbose_name='Surname')
    email = models.EmailField(verbose_name='E-mail')
    contact = models.TextField(verbose_name='Message content')



class TermsAndConditions(models.Model):
    terms = models.TextField()
    privacy = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    title_basic = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)



class Article(models.Model):
    category = models.CharField(max_length=200, verbose_name='Kategoria rankingu')
    name = models.CharField(max_length=200, verbose_name='Główny tytuł wyświetlany w podglądzie',)
    small_description = models.TextField(verbose_name='Krótki opis wyświetlany w podglądzie')
    author = models.CharField(max_length=200, verbose_name='Autor tematu')
    author_img = ProcessedImageField(upload_to='profile-pictures',
                                     verbose_name='Zdjęcie profilowe autora (preferowany rozmiar 200x200)',
                                processors=[ResizeToFill(200, 200)],
                                format='JPEG',
                                options={'quality': 100})
    title = models.CharField(max_length=500, verbose_name='Tytuł')
    basic_img = ProcessedImageField(upload_to='profile-pictures',
                                    verbose_name='Zdjęcie główne (preferowany rozmiar 923x498)',
                                processors=[ResizeToFill(923, 498)],
                                format='JPEG',
                                options={'quality': 100})
    content = RichTextField(verbose_name='Treść tematu')
    slug = models.SlugField(verbose_name="Nazwa wyświetlana w adresie url: http//domain.com/...",)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_at']
        verbose_name = '2A - BLOG - Pozostałe rankingi'
        verbose_name_plural = '2A - BLOG - Pozostałe rankingi'


class ArticleList(models.Model):
    for_article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='Dla artykułu')
    name = models.CharField(max_length=200, verbose_name='Nazwa firmy/Instancji')
    content = models.TextField(blank=True, null=True, verbose_name='Treść/opis (minimalistyczny, przed opisem głównym)')
    image = ProcessedImageField(upload_to='profile-pictures',
                                blank=True, null=True,
                                verbose_name='Zdjęcie główne (preferowany rozmiar 923x328)',
                                processors=[ResizeToFill(928, 328)],
                                format='JPEG',
                                options={'quality': 100})
    logo = ProcessedImageField(upload_to='profile-pictures',
                                blank=True, null=True,
                                verbose_name='Logo',
                                processors=[ResizeToFit(250, 250)],
                                format='JPEG',
                                options={'quality': 100})
    description = RichTextField(blank=True, null=True, verbose_name='Pełna treść (opis główny firmy/isntancji)')

    def __str__(self):
        return '%s - %s' % (self.for_article, self.name)

    class Meta:
        verbose_name = '2B - BLOG - Przedmioty do pozostałych rankingów'
        verbose_name_plural = '2B - BLOG - Przedmioty do pozostałych rankingów'

overview_app/forms.py
from django import forms
from .models import Contact, ContactAdvanced
from django.forms import Textarea



class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = {'name', 'phone', 'data'}


class ContactAdvancedForms(forms.ModelForm):
    class Meta:
        model = ContactAdvanced
        fields = {'name', 'surname', 'email', 'contact'}
        widgets = {'contact': Textarea(attrs={'rows': '6',
                                              'class': 'form-control',
                                              'placeholder': 'Write the content of the message sent to our team...'})}

overview_app/views.py
from django.shortcuts import render
from .forms import ContactForm, ContactAdvancedForms
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Article, TermsAndConditions



def home(request):
    send = request.session.get('send')
    if send:
        request.session['send'] = None

    #contact form
    if request.method == 'POST' and 'buttonSend' in request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['send'] = 'Thank you, the form has been completed correctly. Wait for our employee to contact you.'
            return HttpResponseRedirect(reverse('overview_app:home'))
    else:
        form = ContactForm()

    context = {'send': send,
               'form': form}
    return render(request, 'overview_app/home.html', context)



def contact(request):
    #contact form
    if request.method == 'POST' and 'buttonSend' in request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['send'] = 'Thank you, the form has been completed correctly. Wait for our employee to contact you.'
            return HttpResponseRedirect(reverse('overview_app:home'))
    else:
        form = ContactForm()

    contact_form = ContactAdvancedForms()

    context = {'form': form,
               'contact_form': contact_form}
    return render(request, 'overview_app/contact.html', context)



def pricing(request):
    #contact form
    if request.method == 'POST' and 'buttonSend' in request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['send'] = 'Thank you, the form has been completed correctly. Wait for our employee to contact you.'
            return HttpResponseRedirect(reverse('overview_app:home'))
    else:
        form = ContactForm()

    context = {'form': form}
    return render(request, 'overview_app/pricing.html', context)


def functions(request):
    #functions
    obj = Article.objects.last()

    #contact form
    if request.method == 'POST' and 'buttonSend' in request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['send'] = 'Thank you, the form has been completed correctly. Wait for our employee to contact you.'
            return HttpResponseRedirect(reverse('overview_app:home'))
    else:
        form = ContactForm()

    context = {'form': form,
               'obj': obj}
    return render(request, 'overview_app/functions.html', context)



def vote_for_news(request):
    #contact form
    if request.method == 'POST' and 'buttonSend' in request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['send'] = 'Thank you, the form has been completed correctly. Wait for our employee to contact you.'
            return HttpResponseRedirect(reverse('overview_app:home'))
    else:
        form = ContactForm()

    context = {'form': form}
    return render(request, 'overview_app/vote_for_news.html', context)



def terms(request):
    #specific
    obj = TermsAndConditions.objects.last()

    #contact form
    if request.method == 'POST' and 'buttonSend' in request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['send'] = 'Thank you, the form has been completed correctly. Wait for our employee to contact you.'
            return HttpResponseRedirect(reverse('overview_app:home'))
    else:
        form = ContactForm()

    context = {'form': form,
               'obj': obj}
    return render(request, 'overview_app/terms.html', context)



def privacy(request):
    #specific
    obj = TermsAndConditions.objects.last()

    #contact form
    if request.method == 'POST' and 'buttonSend' in request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['send'] = 'Thank you, the form has been completed correctly. Wait for our employee to contact you.'
            return HttpResponseRedirect(reverse('overview_app:home'))
    else:
        form = ContactForm()

    context = {'form': form,
               'obj': obj}
    return render(request, 'overview_app/privacy.html', context)

overview_app/templates/overview_app/basic/footer.html
{% load static %}
<footer class="py-lg-10 py-5">
  <div class="container">
    <div class="row  justify-content-center text-center  ">
      <div class="col-12 col-md-12 col-xl-8 px-0 ">
        <nav class="nav nav-footer justify-content-center">
          <a class="nav-link" href="{% url 'overview_app:functions' %}">Functionalities </a>
          <a class="nav-link" href="{% url 'overview_app:contact' %}">Contact </a>
          <a class="nav-link" href="{% url 'app:home' %}">Preview app</a>
          <a class="nav-link" href="{% url 'overview_app:terms' %}">Terms</a>
          <a class="nav-link" href="{% url 'overview_app:privacy' %}">Privacy</a>
        </nav>
      </div>
      <!-- Desc -->
      <div class="col-lg-8 col-md-12 col-12">
        <div class="my-6">
          <!--Facebook-->
          <a href="#" class="text-muted me-4">
            <i class="mdi mdi-facebook fs-3"></i>
          </a>
          <!--Twitter-->
          <a href="#" class="text-muted me-4">
            <i class="mdi mdi-twitter  fs-3"></i>
          </a>
          <!--GitHub-->
          <a href="#" class="text-muted me-4">
            <i class="bi bi-tiktok fs-3"></i>
          </a>
          <!--GitHub-->
          <a href="#" class="text-muted">
            <i class="mdi mdi-instagram fs-3"></i>
          </a>
        </div>
      </div>
      <div class="col-lg-8 col-md-12 col-12">
        <span>© 2023 BestCoach, Inc. All Rights Reserved</span>
      </div>
    </div>
  </div>
</footer>

overview_app/templates/overview_app/basic/navbar.html
{% load static %}
{% load crispy_forms_tags %}
<nav class="navbar navbar-expand-lg navbar-default shadow-none">
  <div class="container px-0">
    <a class="navbar-brand" href="{% url 'overview_app:home' %}">
      <img src="{% static 'img/logos/logo_4.png' %}" alt="BestCoach.app - Logo" style="height: 41px;">
    </a>
    
    <!-- Button -->
    <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-default" aria-controls="navbar-default" aria-expanded="false" aria-label="Toggle navigation">
      <span class="icon-bar top-bar mt-0"></span>
      <span class="icon-bar middle-bar"></span>
      <span class="icon-bar bottom-bar"></span>
    </button>
    <!-- Collapse -->
    <div class="collapse navbar-collapse" id="navbar-default">
      <ul class="navbar-nav">
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'overview_app:functions' %}">
            Functions
          </a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'overview_app:contact' %}">
            Contact
          </a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'overview_app:pricing' %}">
            Pricing
          </a>
        </li>
        
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'overview_app:vote_for_news' %}">
            👍 Voting
          </a>
        </li>
        
      </ul>
      
      <div class="ms-auto mt-3 mt-lg-0">
        <div class="d-flex align-items-center">
          <a href="{% url 'app:home' %}" class="btn btn-light me-2">App preview</a>
          <a href="#" class="btn btn-primary ms-1" data-bs-toggle="modal" data-bs-target="#contactModal">Get started</a>
        </div>
      </div>
    </div>
  </div>
</nav>

<!-- Modal -->
<div class="modal fade" id="contactModal" tabindex="-1" aria-labelledby="contactModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Get video presentations!</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form method="POST">
        {% csrf_token %}
        <div class="modal-body">
          <div class="row">
            <div class="col-12">
              <p>Fill out the form below and our employee will call you and present the details and functionality of our application.</p>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              {{ form.name|as_crispy_field }}
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              {{ form.phone|as_crispy_field }}
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              {{ form.data|as_crispy_field }}
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                  I cccepts the regulations and conditions
                </label>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" name="buttonSend">Send form<i class="bi bi-send-check"></i></button>
        </div>
      </form>
    </div>
  </div>
</div>